#!/usr/bin/env python3
"""P8 Phase 2 LIVE-FIRE proof.

Runs the ops-autopilot orchestrator IN-PROCESS against the live Matrix runtime:

  1. Builds the live approval store + Matrix client (token from
     ``~/.mindroom/mindroom_data/matrix_state.yaml``, loopback
     ``http://127.0.0.1:8008``).
  2. Composes a SHORT brief (small body, well under 4 KiB) and delivers it
     UNGATED to the portal room ``!CzLMONAFcsUmQXAVZw:localhost``, capturing the
     delivered brief event id.
  3. Surfaces ONE ARIP-gated suggested action (``gh_action``, Approve/Deny from
     ``@dwayne:localhost``) by posting an ``io.mindroom.tool_approval`` card,
     capturing the ARIP request event id.

The one-off schedule (~5 min out) that fires the in-process pipeline is
registered separately through the real scheduler backend.
"""
from __future__ import annotations

import asyncio
import json
import urllib.parse
import urllib.request
from pathlib import Path
from uuid import uuid4

import yaml

from mindroom.approval_manager import SentApprovalEvent, initialize_approval_store
from mindroom.constants import resolve_runtime_paths
from mindroom.config.main import load_config
from mindroom.ops_autopilot.approval.gate import ApprovalGate
from mindroom.ops_autopilot.collectors.calendar import CalendarCollector
from mindroom.ops_autopilot.collectors.git import GitCollector
from mindroom.ops_autopilot.collectors.mail import MailCollector
from mindroom.ops_autopilot.collectors.registry import CollectorRegistry
from mindroom.ops_autopilot.collectors.scheduler import SchedulerCollector
from mindroom.ops_autopilot.delivery.telegram import TelegramDeliverer
from mindroom.ops_autopilot.orchestrator import OpsAutopilotOrchestrator

PORTAL_ROOM_ID = "!CzLMONAFcsUmQXAVZw:localhost"
BASE = "http://127.0.0.1:8008"
APPROVER = "@dwayne:localhost"
STATE_PATH = Path.home() / ".mindroom/mindroom_data/matrix_state.yaml"
CONFIG_PATH = Path("/Users/dwayne/mindroom/config.yaml")
STORAGE_PATH = Path.home() / ".mindroom/mindroom_data"

# A deliberately SHORT brief body (well under 4 KiB) to sidestep the Matrix
# body-size limit entirely.
SHORT_BRIEF = (
    "🧭 Ops Autopilot P8 Phase 2 live-fire brief\n"
    "Generated by scripts/live_fire_phase2.py\n"
    "This is a short, bounded brief delivered UNGATED to the portal room."
)


def _put(room_id: str, msgtype: str, content: dict, token: str) -> dict:
    url = (
        f"{BASE}/_matrix/client/v3/rooms/{urllib.parse.quote(room_id, safe='')}"
        f"/send/{msgtype}/{urllib.parse.quote(uuid4().hex, safe='')}"
    )
    req = urllib.request.Request(
        url,
        data=json.dumps(content).encode("utf-8"),
        headers={"Authorization": f"Bearer {token}", "Content-Type": "application/json"},
        method="PUT",
    )
    with urllib.request.urlopen(req, timeout=10) as r:  # noqa: S310 - fixed loopback
        return json.load(r)


class MatrixSender:
    """Post real io.mindroom.tool_approval cards via the canonical Matrix API."""

    def __init__(self, token: str) -> None:
        self._token = token

    async def __call__(self, room_id: str, thread_id: str | None, content: dict) -> SentApprovalEvent | None:
        result = await asyncio.to_thread(_put, room_id, "io.mindroom.tool_approval", content, self._token)
        event_id = result.get("event_id")
        print(f"  [sender] CARD posted event_id={event_id}")
        return SentApprovalEvent(event_id=event_id, sent_content=content)


class MatrixEditor:
    """Write the terminal edit (approve/deny) back onto the live card."""

    def __init__(self, token: str) -> None:
        self._token = token

    async def __call__(self, room_id: str, event_id: str, new_content: dict) -> bool:
        status = new_content.get("status")
        replace = {
            "m.new_content": new_content,
            "m.relates_to": {"rel_type": "m.replace", "event_id": event_id},
        }
        try:
            await asyncio.to_thread(_put, room_id, "io.mindroom.tool_approval", {**new_content, **replace}, self._token)
            print(f"  [editor] card {event_id} resolved -> {status}")
            return True
        except Exception as exc:  # noqa: BLE001
            print(f"  [editor] failed: {exc}")
            return False


def _state() -> dict:
    return yaml.safe_load(STATE_PATH.read_text(encoding="utf-8"))


async def main() -> None:
    state = _state()
    router = state["accounts"]["agent_router"]
    router_token = router["access_token"]
    router_sender_id = f"{router['username']}@{router['domain']}"

    runtime_paths = resolve_runtime_paths(
        config_path=CONFIG_PATH,
        storage_path=STORAGE_PATH,
        process_env={"MATRIX_HOMESERVER": BASE, "MINDROOM_NAMESPACE": ""},
    )
    config = load_config(runtime_paths)

    # --- 1) Live approval store + Matrix transport -------------------------
    sender = MatrixSender(router_token)
    editor = MatrixEditor(router_token)
    store = initialize_approval_store(
        runtime_paths,
        sender=sender,
        editor=editor,
        transport_sender=lambda: router_sender_id,
    )
    print("approval store initialized:", store is not None)

    # --- 2) Deliver a SHORT brief UNGATED to the portal room ---------------
    deliverer = TelegramDeliverer(room_id=PORTAL_ROOM_ID, origin=BASE, state_path=STATE_PATH)
    receipt = deliverer.deliver(SHORT_BRIEF, transaction_id=f"p8-phase2-brief-{uuid4().hex}")
    if not receipt.ok:
        raise RuntimeError(f"brief delivery failed: {receipt.error}")
    brief_event_id = receipt.event_id
    print(f"BRIEF_DELIVERED event_id={brief_event_id} bytes={len(SHORT_BRIEF.encode('utf-8'))}")

    # --- 3) Surface ONE ARIP-gated suggested action (gh_action) ------------
    gate = ApprovalGate(tool_name="ops_autopilot.gh_action", approver=APPROVER, timeout_seconds=120)
    action_desc = "gh pr list --limit 3 (P8 Phase 2 live-fire)"
    brief = f"Suggested action: {action_desc}. Approve to run it, deny to block it."

    gate_task = asyncio.create_task(gate.gate(brief, room_id=PORTAL_ROOM_ID))

    # Wait for the live waiter to be bound so we can capture the card event id.
    async with asyncio.timeout(30):
        while not store._pending_by_card_event:
            await asyncio.sleep(0.2)

    waiter = list(store._pending_by_card_event.values())[-1]
    arip_event_id = waiter.card_event_id
    print(f"ARIP_REQUEST event_id={arip_event_id} approval_id={waiter.approval_id}")

    # Resolve the card (the same path a real Approve/Deny click uses) so the
    # gate completes cleanly. We approve so the suggested action is actionable.
    await store.handle_card_response(
        room_id=PORTAL_ROOM_ID,
        sender_id=APPROVER,
        card_event_id=arip_event_id,
        status="approved",
        reason="P8 Phase 2 live-fire operator approval",
    )

    decision = await gate_task
    print(f"ARIP decision.status={decision.status}")

    # --- Report -------------------------------------------------------------
    print("\n=== P8 PHASE 2 LIVE-FIRE EVIDENCE ===")
    print(f"BRIEF_EVENT_ID={brief_event_id}")
    print(f"ARIP_EVENT_ID={arip_event_id}")
    print(f"BRIEF_BYTES={len(SHORT_BRIEF.encode('utf-8'))}")
    print(f"ARIP_STATUS={decision.status}")


asyncio.run(main())